firebase:
  databaseUrl: https://twm-hackerthon-chatter-default-rtdb.asia-southeast1.firebasedatabase.app/
  credentialsPath: ./credentials/twm-hackerthon-chatter-firebase-adminsdk-163ko-4355be3f2d.json