firebase:
  databaseUrl: https://twm-hackerthon-chatter-default-rtdb.asia-southeast1.firebasedatabase.app/
  authKry: AIzaSyAWeg9c1iM5Tp5jmztAWLrf1XvQv5W42Rc
  loginUrl: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=
  signupUrl: https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=
